### ISSUE TITLE
Disable more features in ObjectMapperProvider

### ISSUE THREAD

**Issue by electrum** [airlift/airlift#362]
New features to disable:
* `INFER_PROPERTY_MUTATORS`
* `ALLOW_FINAL_FIELDS_AS_MUTATORS`

**Comment by johngmyers** [comment]
proofpoint/platform@82ab17e25962e635b0d07e4cd76b3d5027a7aae5

**Comment by electrum** [comment]
Thanks @johngmyers, I merged that. It looks like platform is missing `CAN_OVERRIDE_ACCESS_MODIFIERS`: a7aa030c9d6d6d91c5f55977d481ca0bb9dd8c4b

**Comment by johngmyers** [comment]
That is intentional. Jackson should be permitted to override access modifiers. The Jackson annotations indicate the intent for the class to permit such.

A Jackson deserializer is effectively a special type of Builder. It should be unit tested through Jackson, such as through Platform's `JsonTester`. A Jackson serializer similarly needs to be tested through Jackson.

Requiring Jackson methods/constructors/fields to also be public exposes unnecessary implementation details which then require additional otherwise-unnecessary unit tests.
