### ISSUE TITLE
no documents makes me crazy

### ISSUE THREAD

**Issue by zaoshang67dian** [airlift/airlift#753]
I can hardly find the document of AirLift on the web.

**Comment by dain** [comment]
This is a volunteer open source project, and unfortunately no one has spent the time to document it.  If you would like work on documentation, please send a pull request.

**Comment by naivefun** [comment]
This makes it really hard to contribute to Presto project. :(

**Comment by findepi** [comment]
@naivefun Airlift is a broad collection of libraries that are not currently intended for widespread usage.
Currently we devote all our documentation efforts to Presto directly.

I understand the inconvenience it causes to you and that this doesn't answer any of your questions.
Please join [Presto community slack](https://prestosql.io/slack.html) and ask on #dev for Presto-related stuff (Airlift including)
or on #airlift otherwise.
