### ISSUE TITLE
StatusResponseHandler leaks connections

### ISSUE THREAD

**Issue by wagnermarkd** [airlift/airlift#781]
The StatusResponseHandler does not close the input streams on responses. This causes the connection to be held open until the request ultimately times out. If the number of concurrent requests reaches the client's configured limit for connections per host, this can cause requests to queue up.

**Comment by wagnermarkd** [comment]
I've demonstrated this in https://github.com/wagnermarkd/airlift/commit/47a260a7ce31d1b097c6b4770a80b95511d628ee. Updating the StatusResponseHandler to close the stream unblocks the requests, but TestJettyHttpClient.test100kGets consistently fails around request 28k. I haven't had a chance to dig into that.

**Comment by martint** [comment]
The documentation for `InputStreamResponseListener` show this as the canonical way to use it:

```java
InputStreamResponseListener listener = new InputStreamResponseListener();
client.newRequest(...).send(listener);

// Wait for the response headers to arrive
Response response = listener.get(5, TimeUnit.SECONDS);
if (response.getStatus() == 200) {
    // Obtain the input stream on the response content
    try (InputStream input = listener.getInputStream()) {
       // Read the response content
    }
}
```

I don't think it should be the handler's responsibility to close the stream. That should be handled inside `JettyHttpClient`.

I believe the reason those tests are failing is that the handler isn't consuming the response. When the stream is closed, the connection needs to be aborted because it has pending data in the buffer and it can't be reused for other requests. I haven't looked deeply into what's going on under the covers, but I suspect it leaves connections in WAIT state and the process runs out of file descriptors.

**Comment by dain** [comment]
This issue with HTTP 1 is that if you don't drain the stream the client can't reuse the socket, and you have to establish a new one.  This test cycles fast enough that you run out of sockets and the test fails.

**Comment by dain** [comment]
I updated my PR with the drain code as @martint pointed out, and I added the change @wagnermarkd made to the tests.

**Comment by ZacBlanco** [comment]
I've recently been running into issues where queries on a presto cluster begins to fail because I've hit the file descriptor limit. I'm using a 6 node cluster (1 coordinator, 5 workers, m5.xlarge) with AWS EMR 5.25 ([PrestoDB 0.220](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/images/emr-releases-5x.png) which uses [airlift 0.178](https://github.com/prestodb/presto/blob/release-0.220/pom.xml#L47)) and Alluxio. I think part of the reason might be due to some of these sockets being open for a while as described above.

FD limits are set to defaults on the instances, and I start hitting the FD limit at ~4096 open files on the workers. About half of the open files in the JVM are simply references to jar files. The other half I found are actually open sockets.

Here's an image of the data I captured on one of my presto workers. The load over the cluster varied from anywhere between 1 and ~25 concurrently running queries. The queries usually take ~13 seconds to finish.

![image](https://user-images.githubusercontent.com/3464508/70756013-409d4980-1cf0-11ea-9f4e-1b53e823751a.png)

Essentially this graph shows the number of open file descriptors over a time period, with a line for each type. It shows clearly that majority of the open FDs on my presto worker are socket connections.

Here's a snapshot for the output of `sudo lsof -p <Presto worker PID>` at about the 130 mark of the horizontal axis on the graph above where the FD limit was reached.

[134.fd.lsof.txt](https://github.com/airlift/airlift/files/3958165/134.fd.lsof.txt)

Below are a few lines which represent a majority of the entries in the file above:

```
presto-se 10250 presto 3773u     IPv6             319251       0t0      TCP ip-172-31-48-122.ec2.internal:ddi-tcp-2->ip-172-31-59-128.ec2.internal:49782 (ESTABLISHED)
presto-se 10250 presto 3774u     IPv6             414739       0t0      TCP ip-172-31-48-122.ec2.internal:49450->ip-172-31-61-254.ec2.internal:ddi-tcp-2 (ESTABLISHED)
presto-se 10250 presto 3775u     IPv6             417861       0t0      TCP ip-172-31-48-122.ec2.internal:56510->ip-172-31-61-105.ec2.internal:ddi-tcp-2 (ESTABLISHED)
presto-se 10250 presto 3776u     IPv6             416944       0t0      TCP ip-172-31-48-122.ec2.internal:55422->ip-172-31-49-216.ec2.internal:ddi-tcp-2 (ESTABLISHED)
presto-se 10250 presto 3777u     IPv6             416393       0t0      TCP ip-172-31-48-122.ec2.internal:49722->ip-172-31-61-254.ec2.internal:ddi-tcp-2 (ESTABLISHED)
presto-se 10250 presto 3778u     IPv6             414874       0t0      TCP ip-172-31-48-122.ec2.internal:49502->ip-172-31-61-254.ec2.internal:ddi-tcp-2 (ESTABLISHED)
presto-se 10250 presto 3779u     IPv6             313969       0t0      TCP ip-172-31-48-122.ec2.internal:47778->ip-172-31-59-128.ec2.internal:ddi-tcp-2 (ESTABLISHED)
presto-se 10250 presto 3780u     IPv6             315838       0t0      TCP ip-172-31-48-122.ec2.internal:ddi-tcp-2->ip-172-31-59-128.ec2.internal:48746 (ESTABLISHED)
presto-se 10250 presto 3781u     IPv6             415918       0t0      TCP ip-172-31-48-122.ec2.internal:56344->ip-172-31-61-105.ec2.internal:ddi-tcp-2 (ESTABLISHED)
presto-se 10250 presto 3782u     IPv6             315839       0t0      TCP ip-172-31-48-122.ec2.internal:ddi-tcp-2->ip-172-31-49-216.ec2.internal:43824 (ESTABLISHED)
presto-se 10250 presto 3783u     IPv6             313972       0t0      TCP ip-172-31-48-122.ec2.internal:ddi-tcp-2->ip-172-31-48-122.ec2.internal:60782 (ESTABLISHED)
presto-se 10250 presto 3784u     IPv6             315316       0t0      TCP ip-172-31-48-122.ec2.internal:ddi-tcp-2->ip-172-31-59-128.ec2.internal:49718 (ESTABLISHED)
presto-se 10250 presto 3785u     IPv6             314638       0t0      TCP ip-172-31-48-122.ec2.internal:54396->ip-172-31-61-105.ec2.internal:ddi-tcp-2 (ESTABLISHED)
presto-se 10250 presto 3786u     IPv6             416395       0t0      TCP ip-172-31-48-122.ec2.internal:34682->ip-172-31-48-122.ec2.internal:ddi-tcp-2 (ESTABLISHED)
presto-se 10250 presto 3787u     IPv6             314639       0t0      TCP ip-172-31-48-122.ec2.internal:60782->ip-172-31-48-122.ec2.internal:ddi-tcp-2 (ESTABLISHED)
presto-se 10250 presto 3788u     IPv6             314641       0t0      TCP ip-172-31-48-122.ec2.internal:47796->ip-172-31-59-128.ec2.internal:ddi-tcp-2 (ESTABLISHED)
presto-se 10250 presto 3789u     IPv6             418931       0t0      TCP ip-172-31-48-122.ec2.internal:49838->ip-172-31-61-254.ec2.internal:ddi-tcp-2 (ESTABLISHED)
presto-se 10250 presto 3790u     IPv6             314642       0t0      TCP ip-172-31-48-122.ec2.internal:54404->ip-172-31-61-105.ec2.internal:ddi-tcp-2 (ESTABLISHED)
presto-se 10250 presto 3791u     IPv6             315318       0t0      TCP ip-172-31-48-122.ec2.internal:ddi-tcp-2->ip-172-31-61-105.ec2.internal:45414 (ESTABLISHED)
presto-se 10250 presto 3792u     IPv6             415334       0t0      TCP ip-172-31-48-122.ec2.internal:56650->ip-172-31-61-105.ec2.internal:ddi-tcp-2 (ESTABLISHED)
presto-se 10250 presto 3793u     IPv6             411461       0t0      TCP ip-172-31-48-122.ec2.internal:55340->ip-172-31-49-216.ec2.internal:ddi-tcp-2 (ESTABLISHED)
```

The `ddi-tcp-2` for the port represents the [IANA assignment for Port 8889](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=ddi-tcp-2) the port that [PrestoDB is configured to work with on EMR](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-presto-considerations.html)

If I configure [airlift's client timeouts](https://github.com/airlift/airlift/blob/0.178/http-client/src/main/java/io/airlift/http/client/HttpClientConfig.java#L122-L156) To something like 5-15 seconds, do you think it will alleviate the issues? Or do you think the open socket issues I see here are unrelated?

**Comment by dain** [comment]
@ZacBlanco Presto has a recommended  minimum FD limit of 8192:

https://github.com/prestosql/presto/blob/master/presto-main/src/main/java/io/prestosql/server/PrestoSystemRequirements.java#L38

**Comment by dain** [comment]
@wagnermarkd I changed the client to always close the input stream when the requests finishes. I did not add code to drain, because it is not clear that is the right answer in all cases.  For example the server could return a synthetic infinite stream, so the call would never finish.  Also with the multiplexed nature of HTTP/2 I don't think you need to drain the stream.  I also did not change the default status response handler to drain as it is not clear that is the proper handling either.
