### ISSUE TITLE
JettyLogging.java is hostile

### ISSUE THREAD

**Issue by joakime** [airlift/airlift#800]
The forced manual logging done in `JettyLogging.java` is hostile to experienced users, logging configuration should never be done in code.
Leave that for runtime configuration.

That entire file can be replaced with a `jetty-logging.properties` that has 2 lines.

If using java.util.logging directly.

``` properties
org.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.JavaUtilLog
org.eclipse.jetty.util.log.announce=false
```

If using slf4j (which airlift seems to be using)

``` properties
org.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.Slf4jLog
org.eclipse.jetty.util.log.announce=false
```

Plus it can allow users to override airlift logging if they want to (for example when they want to debug things in Jetty, or send logs to alternate locations, or use an alternate logging layer then java.util.logging)

**Comment by joakime** [comment]
This seems to have come about from commit 21a34d8f1ce320d1bbfe3c830b8bc8533e8c26ed which was aimed at client usage, but sadly impacted server usage as well.

**Comment by electrum** [comment]
Thanks for raising this issue. Airlift uses JUL for logging via the `log-manager` module, which also bridges SLF4J, Log4j, and JCL into JUL (by depending on the SLF4J bridges). We all logging to go through JUL.

We use JUL for pragmatic reasons. It's built into the JDK, so it avoids versioning and class loader problems, which is important in applications like Presto that use class loader isolation plugins. The JUL logger API is not great, but that's fine as we have a simple [`Logger`](https://github.com/airlift/airlift/blob/master/log/src/main/java/io/airlift/log/Logger.java) wrapper which allows using standard format strings.

The `http-server` module has a [`jetty-logging.properties`](https://github.com/airlift/airlift/blob/master/http-server/src/main/resources/jetty-logging.properties) as you suggest (thanks for the hint about the `announce` property). The problem is that we have both `http-client` and `http-server` modules which should be independent libraries. Including the same-named property file in both thus causes conflicts when used with [duplicate-finder](https://github.com/basepom/duplicate-finder-maven-plugin) checker.

From an Airlift application's perspective, Jetty should be an implementation detail. Applications do not depend directly on Jetty and should not be required to explicitly configure Jetty's logging.

This approach should not hinder debugging, as the logging can be configured appropriately via JUL. If you want the logging to go somewhere else, you can bridge JUL into e.g., SLF4J, as you would have to do anyway to capture all other JUL logging.

This leads to the question that, if we're already bridging SLF4J, why not remove `jetty-logging.properties` and `JettyLogging` entirely, relying on the default behavior of using `Slf4jLog`? This works for most applications, but it breaks in applications that do not have SLF4J, since Jetty falls back to stderr rather than JUL. This is less of a concern now in practice, as we'd now choose `OkHttp` (or perhaps the JDK `HttpClient`) over Jetty-based `http-client` for such "lightweight" applications, reserving `http-client` for server-to-server where high performance, advanced configuration, request logging, etc., is required.

**Comment by electrum** [comment]
I created #815 based on this discussion. We'll see how others feel about this.
