### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by zaoshang67dian** [airlift/airlift#839]
啥时候提供wiki啊， 开始使用啊， 文档啊！

**Comment by ebyhr** [comment]
I hope you will read this issue https://github.com/airlift/airlift/issues/753.

**Comment by findepi** [comment]
@zaoshang67dian Airlift is a broad collection of libraries that are not currently intended for widespread usage.
Currently we devote all our documentation efforts to Presto directly.

I understand the inconvenience it causes to you.
Please join [Presto community slack](https://prestosql.io/slack.html) and ask on #dev for Presto-related stuff (Airlift including)
or on #airlift otherwise.
