### ISSUE TITLE
the CVE-2020-27218 is fixed in newer version of jetty 9.4.35.v20201120, does airlft need to update the jetty?

### ISSUE THREAD

**Issue by fangcunwangqiu** [airlift/airlift#891]
fixed link： https://github.com/eclipse/jetty.project/security/advisories/GHSA-86wm-rrjm-8wh8

**Comment by findepi** [comment]
From the advisory page:

> The problem can be worked around by either:
> - ...
> - By always fully consuming the request content before sending a response.

which I think _is_ the case in case of Presto (which I guess is your primary concern @fangcunwangqiu, right?).
@electrum would know better though.

Of course, that should not be treated as an argument _against_ upgrading the jetty dependency.

**Comment by fangcunwangqiu** [comment]
> From the advisory page:
> 
> > The problem can be worked around by either:
> > 
> > * ...
> > * By always fully consuming the request content before sending a response.
> 
> which I think _is_ the case in case of Presto (which I guess is your primary concern @fangcunwangqiu, right?).
> @electrum would know better though.
> 
> Of course, that should not be treated as an argument _against_ upgrading the jetty dependency.
:) yes, actually, I am use prestosql, and find the CVE of jetty, so presto depends on airlift, airlift depends on jetty. @findepi

**Comment by electrum** [comment]
From an arbitrary usage of the Airlift HTTP server, it's certainly possible to have a servlet (or probably a JAX-RS handler) that does not consume the body. I remember we had to add code to our internal gateway to explicitly consume and discard the request body when doing an HTTP direct in response to a POST request, in order to avoid some problem. I'm not sure if that scenario is possible in normal usage with JAX-RS, for example, if a JSON parsing error in the middle of a document would stop reading it. Then there's the question of if this behavior could be exploited in a useful way for a specific application.

But regardless of this specific issue, we should keep up to date with Jetty releases. It needs to be tested against [Trino (formerly PrestoSQL)](https://trino.io/) first, since we've seen regressions in the past for Jetty point releases.

**Comment by wendigo** [comment]
This issue can be closed @electrum
